name: First action ever

on:
  workflow_dispatch:
    inputs:
      secret:
        description: 'Enter the secret to deploy'
        type: string
        required: true

jobs:
  first_job:
    name: firstme
    runs-on: ubuntu-latest
    name: First job ever
    steps:
      - name: Test our input
        run: |
          echo "secret=$SECRET"
        env:
          SECRET: ${{ inputs.secret }}
