name: First action ever
on: workflow_dispatch
  inputs:
    secret:
      description: 'Enter the secret to deploy'
      type: string
      required: true
jobs:
  first_job:
    name: First job ever
    steps:
      echo "secret={secret}"
